### ISSUE TITLE
James Denney Resume

### ISSUE THREAD

**Issue by jrdenney** [ga-dc-outcomes/deloitteresume#11]
[James Denney Resume 1017.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1423034/James.Denney.Resume.1017.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! Your resume is really clean - I have just two comments for you.

In your brand statement, change combines and enjoy to "combine" and "enjoy" so that your tenses are consistent.

Take the comma out after Silver Spring, MD in your junior engineer entry so that it's consistent with the rest of your formatting.

Let me know if you have questions.
A

**Comment by jrdenney** [comment]
[James Denney Resume 1017.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1427403/James.Denney.Resume.1017.pdf)
