### ISSUE TITLE
Uraih Resume update

### ISSUE THREAD

**Issue by DataChoo2018** [ga-dc-outcomes/deloitteresume#12]
see attached
[Resume_Uraih 2017 - Deloitte - II.docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1423178/Resume_Uraih.2017.-.Deloitte.-.II.docx)

**Comment by allysonaustin** [comment]
I didn't realized you had submitted a second version!

Swap the order so that brand statement is first and technical skills comes second.

You've got an extra apostrophe in the middle of your brand statement before "conceptualizing."

You've got a "he" in Booz Allen and "his" in NSWC-Carderock. Be sure to change these to "I" and "me."

Let me know if you have questions.
A
