### ISSUE TITLE
Olivo Resume

### ISSUE THREAD

**Issue by nmolivo** [ga-dc-outcomes/deloitteresume#4]
[Natalie_Olivo_resume_201710015.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1422586/Natalie_Olivo_resume_201710015.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a couple of suggestions for you below.

Move your GA section to the top of your experience section, and just add a line-item entry in your education section. This will put your data science experience right at the forefront near your technical skills so that you can demonstrate what you're capable of.

Put an end date on your Lynchval Systems position.

Great work! Let me know if you have questions.
A
