### ISSUE TITLE
Deloitte Resume - DSI 6 - Chukwudi Uraih 

### ISSUE THREAD

**Issue by DataChoo2018** [ga-dc-outcomes/deloitteresume#5]
update attached
[Resume_Uraih 2017 v27OCT2017.docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1422682/Resume_Uraih.2017.v27OCT2017.docx)

**Comment by allysonaustin** [comment]
Thanks for submitting!

I've looked at your response to my previous feedback. I understand the vast amount of previous experience you've had, and that it can be tricky to boil all of that down. I'm still a bit concerned at the length - it's quite overwhelming for the reader and not all of the content is directly relevant. Be really thoughtful about what's necessary and what is extraneous.

You have a few sections that use "he" and "his" instead of "I" and "my."  (Booz Allen & Calderock)

Is your Booz Allen position present? If not, put an end date on it. 

Let me know if you have questions.
A
