### ISSUE TITLE
Masschelin Resume

### ISSUE THREAD

**Issue by ghost** [ga-dc-outcomes/deloitteresume#8]
[Masschelin, Steven, DSI Resume.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1422935/Masschelin.Steven.DSI.Resume.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few notes for you below.

Since you have the space, add your teaching assistant position that you mention under education to your work experience section. Build it out into a complete entry of its own.

You've got a lot of little things that are inconsistent. The first bullet in DSI is spaced differently. The brand statement font is different from the rest, and some of your font sizes are smaller than others. Your dates are formatted slightly differently. These small things can be really distracting for the reader.

Nice work! Let me know if you have questions.
A
